#!/bin/bash
# Public download bootstrap. Network work stays outside the privileged installer.
set -euo pipefail
export PATH=/usr/bin:/bin:/usr/sbin:/sbin LC_ALL=C
unset BASH_ENV ENV CDPATH PERL5OPT PERL5LIB PERLLIB PERL5DB DEVELOPER_DIR SDKROOT TOOLCHAINS
umask 077
readonly setup_version=0.2.0
readonly setup_sha256=c63dd58c7876d209157edc613d730f22d3c5bb5542738f396ed1ce5beb3af4b1
readonly setup_repository=https://github.com/tkddu1591/galaxybridge
setup_directory=

setup::error() { printf 'GalaxyBridge: %s\n' "$*" >&2; return 1; }
setup::cleanup() {
    local result=$?
    trap - EXIT HUP INT TERM
    # This path is generated by mktemp, never supplied by a caller or server.
    if [[ -n "$setup_directory" ]]; then /bin/rm -rf -- "$setup_directory"; fi
    exit "$result"
}
setup::platform::check() {
    (( EUID != 0 )) || { setup::error 'Run this command as your normal user, without sudo.'; return 1; }
    [[ $(/usr/bin/uname -s) == Darwin ]] || { setup::error 'macOS is required.'; return 1; }
    [[ $(/usr/bin/uname -m) == arm64 ]] || { setup::error 'Use a native Apple Silicon terminal (not Intel/Rosetta).'; return 1; }
    local version major minor
    version=$(/usr/bin/sw_vers -productVersion)
    IFS=. read -r major minor _ <<< "$version"
    [[ "$major" =~ ^[0-9]+$ && "$minor" =~ ^[0-9]+$ ]] || return 1
    (( major > 13 || (major == 13 && minor >= 3) )) || { setup::error 'macOS 13.3 or later is required.'; return 1; }
    if [[ -e /Library/PrivilegedHelperTools/io.galaxybridge || -L /Library/PrivilegedHelperTools/io.galaxybridge ]]; then
        setup::error 'GalaxyBridge is already installed. To replace it, first run: sudo /Library/PrivilegedHelperTools/io.galaxybridge/uninstall.sh'
        return 1
    fi
}
setup::download::get() (
    # Bash uses at most 1024-byte file-size units (512 in POSIX mode).
    # Bound disk writes even on old curl versions with chunked responses.
    ulimit -c 0
    ulimit -f 16384
    exec /usr/bin/curl --disable --fail --silent --show-error --location \
        --proto '=https' --proto-redir '=https' --tlsv1.2 \
        --connect-timeout 15 --max-time 180 --max-filesize 16777216 \
        --output "$2" "$1"
)
setup::archive::check() {
    local actual
    actual=$(/usr/bin/shasum -a 256 "$1") || return 1
    [[ "${actual%% *}" == "$setup_sha256" ]] || { setup::error 'Archive checksum mismatch; nothing was installed.'; return 1; }
}
setup::toolchain::check() {
    if /usr/bin/xcode-select -p >/dev/null 2>&1; then return 0; fi
    printf 'Apple Command Line Tools are needed to verify the binary. Complete the Apple installation dialog; setup will wait up to 20 minutes.\n'
    /usr/bin/xcode-select --install || {
        setup::error 'Install Apple Command Line Tools with xcode-select --install, then run the same setup command again.'
        return 1
    }
    local attempt
    for (( attempt=0; attempt<120; attempt++ )); do
        /bin/sleep 10
        if /usr/bin/xcode-select -p >/dev/null 2>&1; then return 0; fi
    done
    setup::error 'Apple tools are not ready yet. Finish their installation and run the same setup command again.'
}
setup::installation::run() {
    local mode=--auto archive bundle
    while (( $# )); do
        case "$1" in
            --manual) mode=manual; shift ;;
            --help|-h)
                printf 'Usage: setup.sh [--manual]\nDownloads and verifies the pinned Apple Silicon release, then installs automatic USB reconnect by default. --manual installs without a background service.\n'
                return 0 ;;
            *) setup::error "Unknown option: $1"; return 1 ;;
        esac
    done
    setup::platform::check
    setup_directory=$(/usr/bin/mktemp -d /private/tmp/galaxybridge-setup.XXXXXXXX)
    trap setup::cleanup EXIT
    trap 'exit 129' HUP
    trap 'exit 130' INT
    trap 'exit 143' TERM
    archive="$setup_directory/release.tar.gz"
    bundle="$setup_directory/galaxybridge-$setup_version-macos-arm64"
    printf 'Downloading GalaxyBridge %s…\n' "$setup_version"
    setup::download::get "$setup_repository/releases/download/v$setup_version/galaxybridge-$setup_version-macos-arm64.tar.gz" "$archive" || {
        setup::error 'The verified release could not be downloaded. It may still be undergoing validation. No administrator authentication or installation was attempted.'
        return 1
    }
    # The expected hash is pinned in this bootstrap, not downloaded beside an
    # arbitrary archive. Only these verified bytes reach tar or the installer.
    setup::archive::check "$archive"
    /usr/bin/tar -xzf "$archive" -C "$setup_directory"
    [[ -f "$bundle/install.sh" && ! -L "$bundle/install.sh" ]] || { setup::error 'Release installer is missing.'; return 1; }
    setup::toolchain::check
    printf 'Archive verified. macOS will request administrator authentication for installation.\n'
    if [[ "$mode" == manual ]]; then
        /bin/bash "$bundle/install.sh"
    else
        /bin/bash "$bundle/install.sh" --auto
    fi
    printf 'Setup complete. Connect your phone and enable USB tethering.\n'
}

setup::installation::run "$@"
