[package]
name = "galaxybridge-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "=0.4.13"
galaxybridge = { path = ".." }

[workspace]
members = ["."]

[[bin]]
name = "protocol"
path = "fuzz_targets/protocol.rs"
test = false
doc = false
bench = false

[[bin]]
name = "usb-layout"
path = "fuzz_targets/usb_layout.rs"
test = false
doc = false
bench = false
